export const motivationalQuotes: string[] = [
  "The only bad workout is the one that didn't happen.",
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "Discipline is choosing between what you want now and what you want most.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Don't stop when you're tired. Stop when you're done.",
  "Success isn't always about greatness. It's about consistency.",
  "The only way to define your limits is by going beyond them.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Sweat is just fat crying.",
  "You don't have to be extreme, just consistent.",
  "Small daily improvements over time lead to stunning results.",
  "The harder you work, the luckier you get.",
  "Your health is an investment, not an expense.",
  "Motivation gets you started. Habit keeps you going.",
  "Be stronger than your excuses.",
  "The best project you'll ever work on is you.",
  "A one-hour workout is 4% of your day. No excuses.",
  "Fall in love with taking care of yourself.",
  "You are one workout away from a good mood.",
  "Believe you can and you're halfway there.",
  "Progress, not perfection.",
  "The body achieves what the mind believes.",
  "Strive for progress, not perfection.",
  "It never gets easier, you just get stronger.",
  "Take care of your body. It's the only place you have to live.",
  "Today's actions are tomorrow's results.",
  "Push yourself because no one else is going to do it for you.",
  "You miss 100% of the workouts you skip.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "The difference between try and triumph is a little umph.",
  "Strength does not come from the physical capacity. It comes from an indomitable will.",
  "Every champion was once a contender that refused to give up.",
  "What seems impossible today will one day be your warm-up.",
  "The secret of getting ahead is getting started.",
  "Great things never come from comfort zones.",
  "Don't wish for it. Work for it.",
  "The only limit is the one you set yourself.",
  "Champions keep playing until they get it right.",
  "If it doesn't challenge you, it doesn't change you.",
  "Your body hears everything your mind says.",
  "Hustle for that muscle.",
  "Good things come to those who sweat.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "No matter how slow you go, you're still lapping everyone on the couch.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "The only person you are destined to become is the one you decide to be.",
  "Workout because you love your body, not because you hate it.",
  "Sore today, strong tomorrow.",
  "Making excuses burns zero calories per hour.",
  "Action is the foundational key to all success.",
  "You're only one workout away from a good mood.",
  "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.",
  "Tough times don't last. Tough people do.",
  "Don't count the days, make the days count.",
  "The will to win means nothing without the will to prepare.",
  "Energy and persistence conquer all things.",
  "Nothing will work unless you do.",
  "When you feel like quitting, remember why you started.",
  "The last three or four reps is what makes the muscle grow.",
  "Once you see results, it becomes an addiction.",
  "Definition of a really good workout: when you hate doing it, but you love finishing it.",
  "Go the extra mile. It's never crowded.",
  "In two weeks, you'll feel it. In four weeks, you'll see it. In eight weeks, you'll hear it.",
  "The groundwork for all happiness is good health.",
  "A year from now you'll wish you had started today.",
  "You don't get what you wish for. You get what you work for.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "We are what we repeatedly do. Excellence then is not an act, but a habit.",
  "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.",
  "The only way to do great work is to love what you do.",
  "Don't let what you cannot do interfere with what you can do.",
  "Winners never quit, and quitters never win.",
  "It's going to be hard, but hard does not mean impossible.",
  "Success starts with self-discipline.",
  "The pain of today is the victory of tomorrow.",
  "Commitment means staying loyal to what you said you were going to do long after the mood you said it in has left you.",
  "Your only limit is you.",
  "Just believe in yourself. Even if you don't, pretend that you do and at some point, you will.",
  "You did not wake up today to be mediocre.",
  "The successful warrior is the average man with laser-like focus.",
  "Rome wasn't built in a day, but they worked on it every day.",
  "Your future self will thank you.",
  "Don't stop until you're proud.",
  "Be patient with yourself. Self-growth is tender.",
  "Today I will do what others won't, so tomorrow I can do what others can't.",
  "Transformation is not a future event. It is a present activity.",
  "The only impossible journey is the one you never begin.",
  "I am not what happened to me. I am what I choose to become.",
  "Start where you are. Use what you have. Do what you can.",
  "Results happen over time, not overnight. Work hard, stay consistent, and be patient.",
];

export function getDailyQuote(dayNumber: number): string {
  return motivationalQuotes[(dayNumber - 1) % motivationalQuotes.length];
}

export function getDailyTip(week: number): string {
  const tips: Record<number, string[]> = {
    1: [
      "Focus on showing up every day — consistency beats intensity in week 1.",
      "Don't worry about being perfect. Just build the habit of moving daily.",
      "Prep your workout clothes the night before to remove friction.",
    ],
    2: [
      "Your muscles are adapting — soreness will decrease soon, keep going!",
      "Start tracking your water intake seriously. Hydration = performance.",
      "Try to establish a fixed workout time that works for your schedule.",
    ],
    3: [
      "This is where most people quit. You're not most people.",
      "Focus on form over reps — quality movement prevents injury.",
      "Start meal prepping to make clean eating easier.",
    ],
    4: [
      "Check your measurements — the scale doesn't tell the whole story.",
      "Increase intensity slightly: shorter rest times or more reps.",
      "Notice how your energy levels have improved since Day 1.",
    ],
    5: [
      "You're a third of the way through. Reflect on your progress!",
      "Try adding a new healthy recipe to keep meals exciting.",
      "Consider taking progress photos to see visual changes.",
    ],
    6: [
      "Time to push harder — your body is ready for more intensity.",
      "Reduce rest times by 10-15 seconds if exercises feel too easy.",
      "Focus on mind-muscle connection during each rep.",
    ],
    7: [
      "Halfway there! Your body has significantly changed by now.",
      "Don't get complacent — increase reps or add a set to key exercises.",
      "Sleep quality matters as much as workout quality.",
    ],
    8: [
      "Major progress milestone! Compare your Week 1 and Week 8 stats.",
      "Challenge yourself with advanced variations of exercises you've mastered.",
      "Your discipline has become a habit. Be proud of that.",
    ],
    9: [
      "The finish line is in sight. Don't slow down now!",
      "Focus on clean eating — nutrition is 80% of the game.",
      "Start thinking about your post-90-day maintenance plan.",
    ],
    10: [
      "Consistency is your superpower. 10 weeks of work speaks volumes.",
      "Try beating your personal records this week.",
      "Visualize your Day 90 self — you're almost there.",
    ],
    11: [
      "One more week to go after this. Give it everything you've got!",
      "Take progress photos and compare with Day 1.",
      "Celebrate small wins — every workout completed is a victory.",
    ],
    12: [
      "Final week! Finish stronger than you started.",
      "This isn't the end — it's the beginning of a lifestyle.",
      "Take your final measurements and celebrate your transformation!",
    ],
  };

  const weekTips = tips[Math.min(week, 12)] || tips[1];
  const dayOfYear = Math.floor(Date.now() / 86400000);
  return weekTips[dayOfYear % weekTips.length];
}
